#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
for i in {1..100}; do
    one=$(( i % 3 ))
    two=$(( i % 5 ))
    if [[ $one == 0 && $two == 0 ]]; then
        echo "FizzBuzz"
    elif [[ $one == 0 ]]; then
        echo "Fizz"
    elif [[ $two == 0 ]]; then
        echo "Buzz"
    else
        echo "$i"
    fi
done
