#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
minutes=1
houres=0
while [ $houres -le 12 ]
do
    echo "Hour: $houres"
    while [ $minutes -le 59 ]
    do
        echo "$minutes"
        (( minutes ++ ))
    done
    minutes=1
    (( houres ++ ))
done
